project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!labs/lab-08b.Rmd"
    - "labs/lab-03.Rmd"
    - "LICENSE.md"

website:
  page-navigation: true
  title: "MAR 536 - Spring 2025"
  description: "Homepage for MAR 536 - Biological Statistics II at UMass Dartmouth, Spring 2025."
  site-url: "https://gavinfay.github.io/mar536-biolstats2-s25"

  repo-url: https://github.com/gavinfay/mar536-biolstats2-s25
  repo-actions: [edit, issue]

  open-graph: true


  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "&copy; Copyright 2025, Gavin Fay. Website structure & design gratefully inspired/made easy by Mine Çetinkaya-Rundel"
    background: "#D9E3E4"

  sidebar:
    background: "#D9E3E4"
    logo: "images/logo.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/gavinfay/mar536-biolstats2-s25
        text: "GitHub"

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - section: "Course information"
        contents:
          - href: course-overview.qmd
            text: Overview
          - href: course-syllabus.qmd
            text: Syllabus
          # - href: course-support.qmd
          #   text: Support
          # - href: course-team.qmd
          #   text: Teaching team
          - href: index.qmd
            text: Schedule
#          - href: course-links.qmd
#            text: Useful links
#          - href: course-faq.qmd
#            text: FAQ
#      - section: "Computing"
#        contents:
#          - href: computing-access.qmd
#            text: Access
#          - href: computing-troubleshooting.qmd
#            text: Troubleshooting
      - section: "Projects"
        contents:
          - href: project-description.qmd
            text: Description
#          - href: project-tips-resources.qmd
#            text: Tips + resources
      - href: midterm.qmd
        text: Midterm exam
      - section: "Weekly materials"
        contents:
          - href: weeks/week-01.qmd
            text: "Week 1"
          - href: weeks/week-02.qmd
            text: "Week 2"
          - href: weeks/week-03.qmd
            text: "Week 3"
          - href: weeks/week-04.qmd
            text: "Week 4"
          - href: weeks/week-05.qmd
            text: "Week 5"
          - href: weeks/week-06.qmd
            text: "Week 6"
          - href: weeks/week-07.qmd
            text: "Week 7"
          - href: weeks/week-08.qmd
            text: "Week 8"
          - href: weeks/week-09.qmd
            text: "Week 9"
#          - href: weeks/week-10.qmd
#            text: "Week 10"
#          - href: weeks/week-11.qmd
#            text: "Week 11"
#          - href: weeks/week-12.qmd
#            text: "Week 12"
#          - href: weeks/week-13.qmd
#            text: "Week 13"
#          - href: weeks/week-14.qmd
#            text: "Week 14"
#          - href: weeks/week-15.qmd
#            text: "Week 15"
#      - section: "Supplemental notes"
#        contents:
      - href: class-data.qmd
        text: Course Data Sets
      #     - href: supplemental/model-diagnostics-matrix.qmd
      #       text: Model diagnostics
      #     - href: supplemental/mlr-matrix.qmd
      #       text: MLR matrix notation
      #     - href: supplemental/log-transformations.qmd
      #       text: Log transformations
      #     - href: supplemental/model-selection-criteria.qmd
      #       text: Model selection criteria

format:
  html:
    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]
    mainfont: "Atkinson Hyperlegible"
    code-copy: true
    code-overflow: wrap
    toc: true

freeze: auto

editor: visual
