---
title: "Project description"
---

Students complete a term project as part of the course. Projects will constitute an advanced statistical analysis of data relevant to the student's graduate research topic, including a detailed report and oral presentation. The project is worth 60% of the course grade.

Students are encouraged to discuss their project ideas with Gavin to identify scope. Note that the project does not have to be related to your graduate research, but many students in previous semesters have found that this is beneficial in developing the basis for their thesis (or a particular chapter). Gavin also has a list of potential student project ideas. Regardless, try to view the project as an analysis that is potentially publishable.

Deliverables include:

1.  1-2 sentence **project topic idea** due Jan 30 (1% of course grade).
2.  Brief (1-2 page) **project** **description** including a statement of the problem, proposed statistical method, and supplemental reference(s) is due Feb 13 (4% of course grade).
3.  **Data exploration report** containing data summaries and visualizations of the dataset to be used in the project, including observations of implications of data structure for the analyses to be conducted, and a **brief in-class update**. Due Feb 27. (10% of course grade).
4.  **In-class verbal update (3 minute presentation)** on project progress. Apr 1. (5% of course grade).
5.  Student **project presentation** with chapter assignment or supplemental reading on the statistical method used in the project. A 10-minute lecture on the method, and demonstration of the method using the project data set. Presentations will be graded based on the instructors' evaluation of accuracy, clarity, and comprehensiveness. Feedback from other students will also be considered in evaluation of presentations (20% of course grade).
6.  **Project report** (due May 02). A written description of the methods and results of the project in the form of a draft scientific manuscript (Introduction, Methods, Results, Discussion). (20% of course grade).

**Project report expectations**

[A rubric for the project report can be found here](documents/MAR536-SPR2023_project-rubric.pdf).

**Project presentation scheduling**

[Go here to complete the survey regarding availability for student presentation time-slots](https://forms.gle/RmMa2Emxit2krdC79).

**Data set ideas**

If you are stuck for a dataset, then there are many open data sets in the ecological and environmental sciences that are published online. Some of these may provide some inspiration for an analysis.

-   [NOAA Data Explorer](https://data.noaa.gov/datasetsearch/)

-   [DOI Data Explorer](https://data.doi.gov/dataset)

-   [Ecological Data Wiki](https://ecologicaldata.org/find-data)

-   [DataDryad](https://datadryad.org/stash)

-   [Zenodo](https://zenodo.org/)

-   [Libguide on ecological datasets from Central Michigan University Library](https://libguides.cmich.edu/lifesciencedata/ecological)
